config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
    resources :rsvps
   
  resources :events do 
   member do
    post 'rsvps', to: 'rsvps#create'
   end
  end
  
  root "events#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
      user ||= User.new 
      if user.admin?
        can :manage, :all
      else
        can :create, Event do |event|
          event.user == user
        end
        can :edit, Event do |event|
          event.user == user
        end
        can :destroy, Event do |event|
          event.user == user
        end
        can :create, Event
        can :read, :all

      end
    
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    acts_as_votable
    geocoded_by :address
    belongs_to :user
    has_many :rsvps
    has_many :users, through: :rsvps

    ##mapping
    
    after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
    
    reverse_geocoded_by :latitude, :longitude
    after_validation :reverse_geocode
    
    
    
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
    belongs_to :event
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_many :rsvps
  
  acts_as_voter
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/concerns/rsvps_controller.rb
class AnswersController < ApplicationController

    def create
        @event      = Event.find(params[:event_id])
        @rsvp       = @event.rsvps.build(rsvps_params)
        @rsvp.user  = current_user
        @rsvp.save  

        redirect_to events_url

    end

    def destroy
        @event = Event.find(params[:event_id])
        @rsvp = @event.rsvps.find(params[:id]).destroy
        redirect_to events_url
    end

    private

        def rsvps_params
            params.require(:rsvp).permit(:content)
        end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :find_event, only: [:show, :edit, :update, :destroy, :upvote]
    before_action :authenticate_user!, except: [:index, :show]
    load_and_authorize_resource

    def index
        @events = Event.all.order("created_at DESC")
    end

    def show
        @event = Event.find params[:id]
        authorize! :read, @article
    end

    def new
        @event = current_user.events.build
    end

    def create
        @event = current_user.events.build(event_params)

        if @event.save
            redirect_to @event, notice: "Great! The event was posted!"
        else
            render 'new'
        end
    end

    def edit 
    end

    def update 
        
        if @event.update(event_params)
            redirect_to @event, notice: "Congrats, Event was updated!"
        else
            render 'edit'
        end
    end

    def destroy 
        @event.destroy
        redirect_to root_path
    end

    def upvote  
        @event.upvote_by current_user
        redirect_to @event
    end

    private

    def event_params
        params.require(:event).permit(:title, :description, :date, :address)
    end

    def find_event
        @event = Event.find(params[:id])
    end
end

app/controllers/rsvp_mail_controller.rb
class Rsvp_MailerController < ApplicationController
    def rsvp
        @rsvp=@event.user
        RsvpMail.rsvp_email(@user).deliver_now
    end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController

    def create
        @rsvps = current_user.rsvps.build({event_id: params[:id]})
       if @rsvps.save
         RsvpMail.rsvp_mail(@user).deliver_now
         flash[:notice] = "You have RSVP'd to this event!"
         redirect_to event_path
       end
    end

    def rsvps
        @rsvps = rsvps.new
    end
  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= simple_form_for @event, html: { multipart: true } do |f|
    - if @event.errors.any?
        #errors
            %h2
            = pluralize(@event.errors.count, "error")
            prevented this Event from saving
            %ul
                - @event.errors.full_messages.each do |msg|
                    %li= msg

    .form-group 
        = f.input :title, input_html: { class: 'form-control' }
    .form-group 
        = f.input :date, datetime_select: { class: 'form-control' }
    .form-group 
        = f.input :address, input_html: { class: 'form-control' }
    .form-group
        = f.input :description, input_html: { class: 'form-control' }

    = f.button :submit, class: "btn btn-info"

app/views/events/edit.html.haml
#edit_underscore.col-md-8.col-md-offset-2
    .row
        .panel.panel-default
            .panel-heading
                %h1 Edit Event
            .panel-body
                = render 'form'

app/views/events/index.html.haml
.col-md-6.col-md-offset-3
  #events.transitions-enabled
    - @events.each do |event| 
      .box.panel.panel-default
        %h2= link_to event.title, event
        

app/views/events/new.html.haml
.col-md-8.col-md-offset-2
    .row
        .panel.panel-default
            .panel-heading
                %h1 Post Event
            .panel-body
                = render 'form'

app/views/events/show.html.haml
#event_show.row
    .col-md-6.col-md-offset-3
        .panel.panel-default
            .panel.body
                %h1= @event.title
                %p= @event.date
                %p= @event.address
                = image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@event.latitude}%2C#{@event.longitude}"
                %p= @event.description
            .panel-footer
                .row
                    .col-md-6
                        %p.user
                            by
                            = @event.user.email
                            
                    .col-md-6
                        .rsvp 
                        = button_to "Click to Rsvp!!!!!", rsvps_event_path(@event), class: "btn btn-primary", style: "margin-bottom: 10px;"
                    
                        -if can? :edit, @event || current_user.admin? 
                            = link_to "Edit", edit_event_path(@event), class: "btn btn-info"
                            |
                        -if can? :destroy, @event || current_user.admin? 
                            = link_to "Delete", event_path(@event), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"
                        

                      

app/views/layouts/application.html.haml
!!!5
%html
%head
  %title Dev Call
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

%body
  %nav.nav.navbar-inverse 
    .container  
      .navbar-brand= link_to "Dev Call", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-left
          %li= link_to "Post an Event!", new_event_path
          %li= link_to "Settings", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete

      - else
        %ul.nav.navbar-nav.navbar-left
          %li= link_to "Join", new_user_registration_path
          %li= link_to "Log In", new_user_session_path
          
  .container
    -flash.each do |name, msg|     
      =content_tag :div, msg, class: "alert alert-info"

  

    = yield

app/views/rsvp_mail/rsvp_mail.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
    </style>
  </head>

  <body>
    <%= yield %>
    <RsvpMail id="rsvp_email"></RsvpMail>

    <h1>Thank you!</h1>

    <p>Thank you for Rsvp'ing to the event! We look forward to seeing you!</p>
!

  </body>
</html>

app/views/rsvp_mail/rsvp_mail.text.erb
Hello!

Thank you for Rsvp'ing to the event! We look forward to seeing you!

Have a great day!

app/views/rsvps/_rsvp.html.erb
<p><%= rsvp.content %>
    <%= link_to "Delete", event_rsvp_path(rsvp.event, rsvp) method: :delete %>
</p>